
version: 1.0.{build}

branches:
  only:
    - master
    - dev

image: Visual Studio 2015

init:
  - set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw64\bin

clone_folder: C:\AuroraFW-build\

install:
  - md C:\AuroraFW-build\bin
  - curl https://raw.githubusercontent.com/esrlabs/git-repo/stable/repo > C:\AuroraFW-build\bin\repo
  - curl https://raw.githubusercontent.com/esrlabs/git-repo/stable/repo.cmd > C:\AuroraFW-build\bin\repo.cmd
  - set PATH=%PATH%;C:\AuroraFW-build\bin
  - repo init -u https://github.com/aurora-fw/manifest.git
  - repo sync
  - pacman -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gtk3 mingw-w64-x86_64-freeimage mingw-w64-x86_64-glew mingw-w64-x86_64-glfw

before_build:
  - cmake .