# ┌─┐┬ ┬┬─┐┌─┐┬─┐┌─┐  ┌─┐┬─┐┌─┐┌┬┐┌─┐┬ ┬┌─┐┬─┐┬┌─
# ├─┤│ │├┬┘│ │├┬┘├─┤  ├┤ ├┬┘├─┤│││├┤ ││││ │├┬┘├┴┐
# ┴ ┴└─┘┴└─└─┘┴└─┴ ┴  └  ┴└─┴ ┴┴ ┴└─┘└┴┘└─┘┴└─┴ ┴
# A Powerful General Purpose Framework
# More information in: https://aurora-fw.github.io/
#
# Copyright (C) 2017 Aurora Framework, All rights reserved.

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

dist: trusty
sudo: required

addons:
 apt:
   sources:
   - kubuntu-backports
   - ubuntu-toolchain-r-test
   packages:
   - build-essential
#   - libgtk-3-dev
   - pkg-config
   - ninja-build
   - cmake
   - libxrandr-dev
   - libxinerama-dev
   - libxcursor-dev
   - libxi-dev
   - libglew-dev

before_install:
  - if [[ "$CC" != "clang" ]]; then sudo apt-get install gcc-7; fi
  - if [[ "$CXX" != "clang++" ]]; then sudo apt-get install g++-7; fi
  - mkdir -p ~/bin
  - PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - yes | repo init -u https://github.com/aurora-fw/manifest.git -b $TRAVIS_BRANCH
  - repo sync -j8
  - repo forall -c repo start $TRAVIS_BRANCH .

before_script:
  - if [[ "$CC" != "clang" ]]; then export CC=/usr/bin/gcc-7; fi
  - if [[ "$CXX" != "clang++" ]]; then export CXX=/usr/bin/g++-7; fi
  - cd $TRAVIS_BUILD_DIR/external
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget http://mirrors.kernel.org/ubuntu/pool/universe/v/vulkan/libvulkan1_1.0.42.0+dfsg1-1ubuntu1~16.04.1_amd64.deb;
      wget http://mirrors.kernel.org/ubuntu/pool/universe/v/vulkan/libvulkan-dev_1.0.42.0+dfsg1-1ubuntu1~16.04.1_amd64.deb;
      wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gtk%2B3.0/libgtk-3-0-udeb_3.22.19-0ubuntu1_amd64.udeb;
      sudo dpkg -i libvulkan1_1.0.42.0+dfsg1-1ubuntu1~16.04.1_amd64.deb libvulkan-dev_1.0.42.0+dfsg1-1ubuntu1~16.04.1_amd64.deb libgtk-3-0-udeb_3.22.19-0ubuntu1_amd64.udeb;
    fi;
  - cd $TRAVIS_BUILD_DIR/external/glfw
  - mkdir -p build && cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} ..
  - cmake --build .
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -DAURORA_BUILD_TEST_APPS=ON .; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then cmake -DCMAKE_BUILD_TYPE=Release -GNinja .; fi
  - ninja && sudo ninja install
  - ninja documentation

notifications:
    email:
        recipients:
            - auroraframework@gmail.com
    on_success: never
    on_failure: always
