# ┌─┐┬ ┬┬─┐┌─┐┬─┐┌─┐  ┌─┐┬─┐┌─┐┌┬┐┌─┐┬ ┬┌─┐┬─┐┬┌─
# ├─┤│ │├┬┘│ │├┬┘├─┤  ├┤ ├┬┘├─┤│││├┤ ││││ │├┬┘├┴┐
# ┴ ┴└─┘┴└─└─┘┴└─┴ ┴  └  ┴└─┴ ┴┴ ┴└─┘└┴┘└─┘┴└─┴ ┴
# A Powerful General Purpose Framework
# More information in: https://aurora-fw.github.io/
#
# Copyright (C) 2017 Aurora Framework, All rights reserved.

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      env: 
        - CXX=g++-7
        - CC=gcc-7

matrix:
  allow_failures:
    - os: osx

sudo: required

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-7
   - g++-7
   - build-essential
   - libgtk-3-dev
   - pkg-config

before_install:
  - mkdir -p ~/bin
  - PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - yes | repo init -u https://github.com/aurora-fw/manifest.git -b $TRAVIS_BRANCH
  - repo sync -j8
  - repo forall -c repo start $TRAVIS_BRANCH .
  - repo forall -c git pull github

install:
  - 

notifications:
    email:
        recipients:
            - auroraframework@gmail.com
    on_success: never
    on_failure: always
